export const logos = [
  require('./../assets/image1-small-23.png'),
  require('./../assets/consulado_del_peru_logo.jpg'),
];

export const images = [
  require('./../assets/machupicchu_thumb.jpg'),
  require('./../assets/machu-picchu-travel.jpg'),
  require('./../assets/consuladoA.jpg'),
  require('./../assets/dancers-gaze.jpg'),
  require('./../assets/fot12.jpg'),
  require('./../assets/fot13-960px.jpg'),
  require('./../assets/foto21.jpg'),
  require('./../assets/foto8.jpg'),
  require('./../assets/presentaciones.jpg'),
];

export const photos = [
  require('./../assets/photos/aprilfestejos.jpg'),
  require('./../assets/photos/consuladoA.jpg'),
  require('./../assets/photos/couple01s.jpg'),
  require('./../assets/photos/couple03s.jpg'),
  require('./../assets/photos/couples05s.jpg'),
  require('./../assets/photos/fot10b.jpg'),
  require('./../assets/photos/fot11b.jpg'),
  require('./../assets/photos/fot12b.jpg'),
  require('./../assets/photos/fot13b.jpg'),
  require('./../assets/photos/fot14b.jpg'),
  require('./../assets/photos/fot1b_.jpg'),
  require('./../assets/photos/fot2b.jpg'),
  require('./../assets/photos/fot3b.jpg'),
  require('./../assets/photos/fot4b.jpg'),
  require('./../assets/photos/fot5b.jpg'),
  require('./../assets/photos/fot6b.jpg'),
  require('./../assets/photos/fot7b.jpg'),
  require('./../assets/photos/fot8b.jpg'),
  require('./../assets/photos/fot9b.jpg'),
  require('./../assets/photos/foto1.jpg'),
  require('./../assets/photos/foto10.jpg'),
  require('./../assets/photos/foto11.jpg'),
  require('./../assets/photos/foto12.jpg'),
  require('./../assets/photos/foto13.jpg'),
  require('./../assets/photos/foto14.jpg'),
  require('./../assets/photos/foto15.jpg'),
  require('./../assets/photos/foto16.jpg'),
  require('./../assets/photos/foto17.jpg'),
  require('./../assets/photos/foto18.jpg'),
  require('./../assets/photos/foto19.jpg'),
  require('./../assets/photos/foto2.jpg'),
  require('./../assets/photos/foto20.jpg'),
  require('./../assets/photos/foto21.jpg'),
  require('./../assets/photos/foto22.jpg'),
  require('./../assets/photos/foto23-small.jpg'),
  require('./../assets/photos/foto24-small.jpg'),
  require('./../assets/photos/foto25.jpg'),
  require('./../assets/photos/foto26.jpg'),
  require('./../assets/photos/foto27-small.jpg'),
  require('./../assets/photos/foto28-small.jpg'),
  require('./../assets/photos/foto3.jpg'),
  require('./../assets/photos/foto30-small.jpg'),
  require('./../assets/photos/foto31-small.jpg'),
  require('./../assets/photos/foto4.jpg'),
  require('./../assets/photos/foto5b.jpg'),
  require('./../assets/photos/foto6.jpg'),
  require('./../assets/photos/foto8.jpg'),
  require('./../assets/photos/foto9.jpg'),
  require('./../assets/photos/fotohome2.jpg'),
  require('./../assets/photos/jeanineprimeras.jpg'),
  require('./../assets/photos/margotts.jpg'),
  require('./../assets/photos/semblanzagaleriasmall.jpg'),
];

export const dancers = [
  require('./../assets/dancers/dancing04s.jpg'),
  require('./../assets/dancers/group01s.jpg'),
  require('./../assets/dancers/group02s.jpg'),
  require('./../assets/dancers/group03s.jpg'),
  require('./../assets/dancers/group05s.jpg'),
  require('./../assets/dancers/group06s.jpg'),
  require('./../assets/dancers/group07s.jpg'),
  require('./../assets/dancers/group08s.jpg'),
  require('./../assets/dancers/group09s.jpg'),
  require('./../assets/dancers/group10s.jpg'),
  require('./../assets/dancers/jeanine01s.jpg'),
  require('./../assets/dancers/margott01s.jpg'),
];

export const history = [
  require('./../assets/history/girl_scanned_01s.jpg'),
  require('./../assets/history/girls_scanned_01s.jpg'),
  require('./../assets/history/girls_scanned_02s.jpg'),
  require('./../assets/history/girls_scanned_03s.jpg'),
  require('./../assets/history/group_scanned_01s.jpg'),
  require('./../assets/history/group_scanned_02s.jpg'),
  require('./../assets/history/group_scanned_03s.jpg'),
  require('./../assets/history/group_scanned_04s.jpg'),
  require('./../assets/history/group_scanned_05s.jpg'),
  require('./../assets/history/group_scanned_06s.jpg'),
  require('./../assets/history/jeanine_scanned_01s.jpg'),
  require('./../assets/history/jeanine_scanned_02s.jpg'),
  require('./../assets/history/jeanine_scanned_03s.jpg'),
];

export const presentations = [
  require('./../assets/presentations/TulioLoza.jpg'),
  require('./../assets/presentations/ceciliabarrazasmall.jpg'),
  require('./../assets/presentations/desfile.jpg'),
  require('./../assets/presentations/discoverperu.jpg'),
  require('./../assets/presentations/evento2011.jpg'),
  require('./../assets/presentations/eventomarzo2014.jpg'),
  require('./../assets/presentations/festival.jpg'),
  require('./../assets/presentations/homenaje.jpg'),
  require('./../assets/presentations/inkaevent.jpg'),
  require('./../assets/presentations/raicesperuanas.jpg'),
  require('./../assets/presentations/reportaje.jpg'),
  require('./../assets/presentations/semblanza2.jpg'),
];
